name: einspection
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  dropdown_button2: ^2.3.9
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.2
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  image: ^4.1.7
  flutter_datawedge: ^2.1.0
  double_tap_to_exit: ^1.0.1
  intl: ^0.19.0
  data_table_2: ^2.5.11
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
  